package com.bytedance.android.live.base.model.proto;

import com.bytedance.android.livesdk.chatroom.model.C4869ad;
import com.bytedance.android.livesdk.chatroom.model.C4871af;
import com.bytedance.android.livesdk.chatroom.model.C4872ag;
import com.bytedance.android.livesdk.chatroom.model.C4873ah;
import com.bytedance.android.livesdk.chatroom.model.C4895ba;
import com.bytedance.android.livesdk.chatroom.model.C4896bb;
import com.bytedance.android.livesdk.chatroom.model.C4897bc;
import com.bytedance.android.livesdk.chatroom.model.C4898bd;
import com.bytedance.android.livesdk.chatroom.model.p219a.C4851c;
import com.bytedance.android.livesdk.chatroom.model.p219a.C4851c.C4852a;
import com.bytedance.android.livesdk.chatroom.model.p219a.C4862m;
import com.bytedance.android.livesdk.chatroom.model.p219a.C4863n;
import com.bytedance.android.livesdk.message.model.C8478af;
import com.bytedance.android.livesdk.message.model.C8478af.C8479a;
import com.bytedance.android.livesdk.message.model.C8480ag;
import com.bytedance.android.livesdk.message.model.C8482ai;
import com.bytedance.android.livesdk.message.model.C8486al;
import com.bytedance.android.livesdk.message.model.C8491aq;
import com.bytedance.android.livesdk.message.model.C8492ar;
import com.bytedance.android.livesdk.message.model.C8494at;
import com.bytedance.android.livesdk.message.model.C8495au;
import com.bytedance.android.livesdk.message.model.C8498ax;
import com.bytedance.android.livesdk.message.model.C8499ay;
import com.bytedance.android.livesdk.message.model.C8499ay.C8500a;
import com.bytedance.android.livesdk.message.model.C8499ay.C8500a.C8501a;
import com.bytedance.android.livesdk.message.model.C8502az;
import com.bytedance.android.livesdk.message.model.C8504ba;
import com.bytedance.android.livesdk.message.model.C8506bc;
import com.bytedance.android.livesdk.message.model.C8508bd;
import com.bytedance.android.livesdk.message.model.C8509be;
import com.bytedance.android.livesdk.message.model.C8510bf;
import com.bytedance.android.livesdk.message.model.C8511bg;
import com.bytedance.android.livesdk.message.model.C8512bh;
import com.bytedance.android.livesdk.message.model.C8513bi;
import com.bytedance.android.livesdk.message.model.C8516bk;
import com.bytedance.android.livesdk.message.model.C8527bq;
import com.bytedance.android.livesdk.message.model.C8528br;
import com.bytedance.android.livesdk.message.model.C8529bs;
import com.bytedance.android.livesdk.message.model.C8536bz;
import com.bytedance.android.livesdk.message.model.C8536bz.C8537a;
import com.bytedance.android.livesdk.message.model.C8541cc;
import com.bytedance.android.livesdk.message.model.C8542cd;
import com.bytedance.android.livesdk.message.model.C8543ce;
import com.bytedance.android.livesdk.message.model.C8544cf;
import com.bytedance.android.livesdk.message.model.C8545cg;
import com.bytedance.android.livesdk.message.model.C8546ch;
import com.bytedance.android.livesdk.message.model.C8547ci;
import com.bytedance.android.livesdk.message.model.C8548cj;
import com.bytedance.android.livesdk.message.model.C8550cl;
import com.bytedance.android.livesdk.message.model.C8553cn;
import com.bytedance.android.livesdk.message.model.C8554co;
import com.bytedance.android.livesdk.message.model.C8555cp;
import com.bytedance.android.livesdk.message.model.C8556cq;
import com.bytedance.android.livesdk.message.model.C8559cs;
import com.bytedance.android.livesdk.message.model.C8560ct;
import com.bytedance.android.livesdk.message.model.C8566cz;
import com.bytedance.android.livesdk.message.model.C8571dd;
import com.bytedance.android.livesdk.message.model.C8572de;
import com.bytedance.android.livesdk.message.model.C8575dh;
import com.bytedance.android.livesdk.message.model.C8578dk;
import com.bytedance.android.livesdk.message.model.C8579dl;
import com.bytedance.android.livesdk.message.model.C8580dm;
import com.bytedance.android.livesdk.message.model.C8583dp;
import com.bytedance.android.livesdk.message.model.C8584dq;
import com.bytedance.android.livesdk.message.model.C8586dr;
import com.bytedance.android.livesdk.message.model.C8587ds;
import com.bytedance.android.livesdk.message.model.C8593dx;
import com.bytedance.android.livesdk.message.model.C8594dy;
import com.bytedance.android.livesdk.message.model.C8595dz;
import com.bytedance.android.livesdk.message.model.C8597ea;
import com.bytedance.android.livesdk.message.model.C8599ec;
import com.bytedance.android.livesdk.message.model.C8603eg;
import com.bytedance.android.livesdk.message.model.C8607ek;
import com.bytedance.android.livesdk.message.model.C8608el;
import com.bytedance.android.livesdk.message.model.C8610en;
import com.bytedance.android.livesdk.message.model.C8611eo;
import com.bytedance.android.livesdk.message.model.C8613eq;
import com.bytedance.android.livesdk.message.model.C8614er;
import com.bytedance.android.livesdk.message.model.C8615es;
import com.bytedance.android.livesdk.message.model.C8616et;
import com.bytedance.android.livesdk.message.model.C8617eu;
import com.bytedance.android.livesdk.message.model.C8618ev;
import com.bytedance.android.livesdk.message.model.C8620ex;
import com.bytedance.android.livesdk.message.model.C8621ey;
import com.bytedance.android.livesdk.message.model.C8622ez;
import com.bytedance.android.livesdk.message.model.C8624fa;
import com.bytedance.android.livesdk.message.model.C8625fb;
import com.bytedance.android.livesdk.message.model.C8627fd;
import com.bytedance.android.livesdk.message.model.C8628fe;
import com.bytedance.android.livesdk.message.model.C8631fh;
import com.bytedance.android.livesdk.message.model.C8641fr;
import com.bytedance.android.livesdk.message.model.C8642fs;
import com.bytedance.android.livesdk.message.model.C8643ft;
import com.bytedance.android.livesdk.message.model.C8650g;
import com.bytedance.android.livesdk.message.model.C8651ga;
import com.bytedance.android.livesdk.message.model.C8652gb;
import com.bytedance.android.livesdk.message.model.C8654gd;
import com.bytedance.android.livesdk.message.model.C8655ge;
import com.bytedance.android.livesdk.message.model.C8656gf;
import com.bytedance.android.livesdk.message.model.C8657gg;
import com.bytedance.android.livesdk.message.model.C8658gh;
import com.bytedance.android.livesdk.message.model.C8659gi;
import com.bytedance.android.livesdk.message.model.C8660gj;
import com.bytedance.android.livesdk.message.model.C8661gk;
import com.bytedance.android.livesdk.message.model.C8662gl;
import com.bytedance.android.livesdk.message.model.C8663gm;
import com.bytedance.android.livesdk.message.model.C8664gn;
import com.bytedance.android.livesdk.message.model.C8667gq;
import com.bytedance.android.livesdk.message.model.C8668gr;
import com.bytedance.android.livesdk.message.model.C8669gs;
import com.bytedance.android.livesdk.message.model.C8670gt;
import com.bytedance.android.livesdk.message.model.C8673gw;
import com.bytedance.android.livesdk.message.model.C8674gx;
import com.bytedance.android.livesdk.message.model.C8678k;
import com.bytedance.android.livesdk.message.model.C8679l;
import com.bytedance.android.livesdk.message.model.C8682o;
import com.bytedance.android.livesdk.message.model.C8685q;
import com.bytedance.android.livesdk.message.model.C8686r;
import com.bytedance.android.livesdk.message.model.C8687s;
import com.bytedance.android.livesdk.message.model.C8690u;
import com.bytedance.android.livesdk.message.model.C8691v;
import com.bytedance.android.livesdk.message.model.C8693x;
import com.bytedance.android.livesdk.message.model.C8695y;
import com.bytedance.android.livesdk.message.model.FansclubStatisticMessage;
import com.bytedance.android.livesdk.message.model.RoomNotifyMessageExtra;
import com.bytedance.android.livesdk.message.model.RoomNotifyMessageExtra.Background;
import com.bytedance.android.p109c.p110a.p111a.C2265b;
import java.util.HashMap;
import java.util.Map;

/* renamed from: com.bytedance.android.live.base.model.proto.d */
public final class C2364d {

    /* renamed from: a */
    private static final Map<Class, C2265b> f7788a = new HashMap();

    /* renamed from: a */
    public static void m9967a(Map<Class, C2265b> map) {
        map.put(C4851c.class, new C4862m());
        map.put(C4852a.class, new C4863n());
        map.put(C4869ad.class, new C4895ba());
        map.put(C4872ag.class, new C4897bc());
        map.put(C4871af.class, new C4896bb());
        map.put(C4873ah.class, new C4898bd());
        map.put(C8691v.class, new C8584dq());
        map.put(RoomNotifyMessageExtra.class, new C8658gh());
        map.put(Background.class, new C8657gg());
        map.put(C8482ai.class, new C8599ec());
        map.put(C8478af.class, new C8593dx());
        map.put(C8479a.class, new C8594dy());
        map.put(C8543ce.class, new C8656gf());
        map.put(C8545cg.class, new C8660gj());
        map.put(C8508bd.class, new C8621ey());
        map.put(C8687s.class, new C8580dm());
        map.put(C8494at.class, new C8610en());
        map.put(C8495au.class, new C8611eo());
        map.put(C8511bg.class, new C8625fb());
        map.put(C8559cs.class, new C8673gw());
        map.put(C8528br.class, new C8642fs());
        map.put(C8542cd.class, new C8655ge());
        map.put(FansclubStatisticMessage.class, new C8597ea());
        map.put(C8516bk.class, new C8631fh());
        map.put(C8693x.class, new C8586dr());
        map.put(C8560ct.class, new C8674gx());
        map.put(C8502az.class, new C8617eu());
        map.put(C8686r.class, new C8579dl());
        map.put(C8650g.class, new C8566cz());
        map.put(C8682o.class, new C8575dh());
        map.put(C8504ba.class, new C8618ev());
        map.put(C8506bc.class, new C8620ex());
        map.put(C8556cq.class, new C8670gt());
        map.put(C8498ax.class, new C8613eq());
        map.put(C8685q.class, new C8578dk());
        map.put(C8544cf.class, new C8659gi());
        map.put(C8510bf.class, new C8624fa());
        map.put(C8546ch.class, new C8661gk());
        map.put(C8679l.class, new C8572de());
        map.put(C8486al.class, new C8603eg());
        map.put(C8491aq.class, new C8607ek());
        map.put(C8548cj.class, new C8663gm());
        map.put(C8509be.class, new C8622ez());
        map.put(C8512bh.class, new C8627fd());
        map.put(C8529bs.class, new C8643ft());
        map.put(C8678k.class, new C8571dd());
        map.put(C8499ay.class, new C8614er());
        map.put(C8500a.class, new C8615es());
        map.put(C8501a.class, new C8616et());
        map.put(C8541cc.class, new C8654gd());
        map.put(C8555cp.class, new C8669gs());
        map.put(C8536bz.class, new C8651ga());
        map.put(C8537a.class, new C8652gb());
        map.put(C8550cl.class, new C8664gn());
        map.put(C8690u.class, new C8583dp());
        map.put(C8480ag.class, new C8595dz());
        map.put(C8513bi.class, new C8628fe());
        map.put(C8547ci.class, new C8662gl());
        map.put(C8527bq.class, new C8641fr());
        map.put(C8695y.class, new C8587ds());
        map.put(C8553cn.class, new C8667gq());
        map.put(C8554co.class, new C8668gr());
        map.put(C8492ar.class, new C8608el());
    }
}
