package com.bytedance.android.live.base.model.proto;

import com.bytedance.android.livesdk.chatroom.interact.model.C4818c;
import com.bytedance.android.livesdk.chatroom.interact.model.RivalExtraInfo;
import com.bytedance.android.livesdk.chatroom.model.C4891ax;
import com.bytedance.android.livesdk.chatroom.model.C4892ay;
import com.bytedance.android.livesdk.chatroom.model.C4893az;
import com.bytedance.android.livesdk.chatroom.model.C4894b;
import com.bytedance.android.livesdk.chatroom.model.C4899c;
import com.bytedance.android.livesdk.chatroom.model.C4899c.C4900a;
import com.bytedance.android.livesdk.chatroom.model.p219a.C4861l;
import com.bytedance.android.livesdk.chatroom.model.p219a.C4864o;
import com.bytedance.android.livesdk.gift.relay.p392a.C8269a;
import com.bytedance.android.livesdk.gift.relay.p392a.C8273d;
import com.bytedance.android.livesdk.message.model.C8472a;
import com.bytedance.android.livesdk.message.model.C8475ac;
import com.bytedance.android.livesdk.message.model.C8476ad;
import com.bytedance.android.livesdk.message.model.C8477ae;
import com.bytedance.android.livesdk.message.model.C8481ah;
import com.bytedance.android.livesdk.message.model.C8483aj;
import com.bytedance.android.livesdk.message.model.C8484ak;
import com.bytedance.android.livesdk.message.model.C8484ak.C8485a;
import com.bytedance.android.livesdk.message.model.C8488an;
import com.bytedance.android.livesdk.message.model.C8489ao;
import com.bytedance.android.livesdk.message.model.C8490ap;
import com.bytedance.android.livesdk.message.model.C8493as;
import com.bytedance.android.livesdk.message.model.C8496av;
import com.bytedance.android.livesdk.message.model.C8503b;
import com.bytedance.android.livesdk.message.model.C8505bb;
import com.bytedance.android.livesdk.message.model.C8514bj;
import com.bytedance.android.livesdk.message.model.C8514bj.C8515a;
import com.bytedance.android.livesdk.message.model.C8517bl;
import com.bytedance.android.livesdk.message.model.C8518bm;
import com.bytedance.android.livesdk.message.model.C8519bn;
import com.bytedance.android.livesdk.message.model.C8520bo;
import com.bytedance.android.livesdk.message.model.C8520bo.C8521a;
import com.bytedance.android.livesdk.message.model.C8522bp;
import com.bytedance.android.livesdk.message.model.C8522bp.C8524b;
import com.bytedance.android.livesdk.message.model.C8522bp.C8525c;
import com.bytedance.android.livesdk.message.model.C8522bp.C8526d;
import com.bytedance.android.livesdk.message.model.C8530bt;
import com.bytedance.android.livesdk.message.model.C8531bu;
import com.bytedance.android.livesdk.message.model.C8532bv;
import com.bytedance.android.livesdk.message.model.C8533bw;
import com.bytedance.android.livesdk.message.model.C8534bx;
import com.bytedance.android.livesdk.message.model.C8539ca;
import com.bytedance.android.livesdk.message.model.C8540cb;
import com.bytedance.android.livesdk.message.model.C8551cm;
import com.bytedance.android.livesdk.message.model.C8551cm.C8552a;
import com.bytedance.android.livesdk.message.model.C8557cr;
import com.bytedance.android.livesdk.message.model.C8557cr.C8558a;
import com.bytedance.android.livesdk.message.model.C8561cu;
import com.bytedance.android.livesdk.message.model.C8562cv;
import com.bytedance.android.livesdk.message.model.C8563cw;
import com.bytedance.android.livesdk.message.model.C8564cx;
import com.bytedance.android.livesdk.message.model.C8565cy;
import com.bytedance.android.livesdk.message.model.C8567d;
import com.bytedance.android.livesdk.message.model.C8568da;
import com.bytedance.android.livesdk.message.model.C8569db;
import com.bytedance.android.livesdk.message.model.C8570dc;
import com.bytedance.android.livesdk.message.model.C8573df;
import com.bytedance.android.livesdk.message.model.C8574dg;
import com.bytedance.android.livesdk.message.model.C8576di;
import com.bytedance.android.livesdk.message.model.C8577dj;
import com.bytedance.android.livesdk.message.model.C8581dn;
import com.bytedance.android.livesdk.message.model.C8582do;
import com.bytedance.android.livesdk.message.model.C8588dt;
import com.bytedance.android.livesdk.message.model.C8590du;
import com.bytedance.android.livesdk.message.model.C8591dv;
import com.bytedance.android.livesdk.message.model.C8592dw;
import com.bytedance.android.livesdk.message.model.C8596e;
import com.bytedance.android.livesdk.message.model.C8598eb;
import com.bytedance.android.livesdk.message.model.C8600ed;
import com.bytedance.android.livesdk.message.model.C8601ee;
import com.bytedance.android.livesdk.message.model.C8602ef;
import com.bytedance.android.livesdk.message.model.C8604eh;
import com.bytedance.android.livesdk.message.model.C8605ei;
import com.bytedance.android.livesdk.message.model.C8606ej;
import com.bytedance.android.livesdk.message.model.C8609em;
import com.bytedance.android.livesdk.message.model.C8612ep;
import com.bytedance.android.livesdk.message.model.C8619ew;
import com.bytedance.android.livesdk.message.model.C8623f;
import com.bytedance.android.livesdk.message.model.C8626fc;
import com.bytedance.android.livesdk.message.model.C8629ff;
import com.bytedance.android.livesdk.message.model.C8630fg;
import com.bytedance.android.livesdk.message.model.C8632fi;
import com.bytedance.android.livesdk.message.model.C8633fj;
import com.bytedance.android.livesdk.message.model.C8634fk;
import com.bytedance.android.livesdk.message.model.C8635fl;
import com.bytedance.android.livesdk.message.model.C8636fm;
import com.bytedance.android.livesdk.message.model.C8637fn;
import com.bytedance.android.livesdk.message.model.C8638fo;
import com.bytedance.android.livesdk.message.model.C8639fp;
import com.bytedance.android.livesdk.message.model.C8640fq;
import com.bytedance.android.livesdk.message.model.C8644fu;
import com.bytedance.android.livesdk.message.model.C8645fv;
import com.bytedance.android.livesdk.message.model.C8646fw;
import com.bytedance.android.livesdk.message.model.C8647fx;
import com.bytedance.android.livesdk.message.model.C8648fy;
import com.bytedance.android.livesdk.message.model.C8649fz;
import com.bytedance.android.livesdk.message.model.C8653gc;
import com.bytedance.android.livesdk.message.model.C8665go;
import com.bytedance.android.livesdk.message.model.C8666gp;
import com.bytedance.android.livesdk.message.model.C8671gu;
import com.bytedance.android.livesdk.message.model.C8672gv;
import com.bytedance.android.livesdk.message.model.C8675h;
import com.bytedance.android.livesdk.message.model.C8676i;
import com.bytedance.android.livesdk.message.model.C8677j;
import com.bytedance.android.livesdk.message.model.C8680m;
import com.bytedance.android.livesdk.message.model.C8681n;
import com.bytedance.android.livesdk.message.model.C8683p;
import com.bytedance.android.livesdk.message.model.C8683p.C8684a;
import com.bytedance.android.livesdk.message.model.C8688t;
import com.bytedance.android.livesdk.message.model.C8688t.C8689a;
import com.bytedance.android.livesdk.message.model.C8696z;
import com.bytedance.android.livesdk.message.model.LotteryEventMessage;
import com.bytedance.android.p109c.p110a.p111a.C2265b;
import java.util.HashMap;
import java.util.Map;

/* renamed from: com.bytedance.android.live.base.model.proto.e */
public final class C2365e {

    /* renamed from: a */
    private static final Map<Class, C2265b> f7789a = new HashMap();

    /* renamed from: a */
    public static void m9968a(Map<Class, C2265b> map) {
        map.put(C8269a.class, new C8273d());
        map.put(C8477ae.class, new C8592dw());
        map.put(C8681n.class, new C8574dg());
        map.put(C8551cm.class, new C8666gp());
        map.put(C8552a.class, new C8665go());
        map.put(C8472a.class, new C8561cu());
        map.put(C8496av.class, new C8612ep());
        map.put(LotteryEventMessage.class, new C8626fc());
        map.put(C8483aj.class, new C8600ed());
        map.put(C8675h.class, new C8568da());
        map.put(C8489ao.class, new C8605ei());
        map.put(C8688t.class, new C8582do());
        map.put(C8689a.class, new C8581dn());
        map.put(C8493as.class, new C8609em());
        map.put(C8484ak.class, new C8602ef());
        map.put(C8485a.class, new C8601ee());
        map.put(C8514bj.class, new C8630fg());
        map.put(C8515a.class, new C8629ff());
        map.put(C8539ca.class, new C8649fz());
        map.put(C8531bu.class, new C8645fv());
        map.put(C8519bn.class, new C8634fk());
        map.put(C8505bb.class, new C8619ew());
        map.put(C8476ad.class, new C8591dv());
        map.put(C8481ah.class, new C8598eb());
        map.put(C8676i.class, new C8569db());
        map.put(C8475ac.class, new C8590du());
        map.put(C8696z.class, new C8588dt());
        map.put(C8596e.class, new C8564cx());
        map.put(C8503b.class, new C8562cv());
        map.put(C8532bv.class, new C8647fx());
        map.put(C8520bo.class, new C8636fm());
        map.put(C8521a.class, new C8635fl());
        map.put(C8683p.class, new C8577dj());
        map.put(C8684a.class, new C8576di());
        map.put(C8518bm.class, new C8633fj());
        map.put(C8677j.class, new C8570dc());
        map.put(C8540cb.class, new C8653gc());
        map.put(C8557cr.class, new C8672gv());
        map.put(C8558a.class, new C8671gu());
        map.put(C8623f.class, new C8565cy());
        map.put(C8534bx.class, new C8648fy());
        map.put(C8680m.class, new C8573df());
        map.put(C8517bl.class, new C8632fi());
        map.put(C8490ap.class, new C8606ej());
        map.put(C8533bw.class, new C8646fw());
        map.put(C8567d.class, new C8563cw());
        map.put(C8530bt.class, new C8644fu());
        map.put(C8488an.class, new C8604eh());
        map.put(C8522bp.class, new C8640fq());
        map.put(C8524b.class, new C8637fn());
        map.put(C8526d.class, new C8639fp());
        map.put(C8525c.class, new C8638fo());
        map.put(C4899c.class, new C4893az());
        map.put(C4900a.class, new C4892ay());
        map.put(C4894b.class, new C4891ax());
        map.put(C4861l.class, new C4864o());
        map.put(RivalExtraInfo.class, new C4818c());
    }
}
