package com.google.android.gms.common.api.internal;

import com.google.android.gms.common.api.C15041e;
import com.google.android.gms.common.api.C15041e.C15042a;
import com.google.android.gms.common.api.C15044g;
import com.google.android.gms.common.api.C15045h;
import com.google.android.gms.common.api.Status;

/* renamed from: com.google.android.gms.common.api.internal.bo */
public final class C15092bo<R extends C15044g> extends C15041e<R> {

    /* renamed from: a */
    public final Status f39027a;

    /* renamed from: a */
    public final void mo38260a() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* renamed from: b */
    public final boolean mo38263b() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* renamed from: a */
    public final void mo38262a(C15045h<? super R> hVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* renamed from: a */
    public final void mo38261a(C15042a aVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* renamed from: c */
    public final Integer mo38264c() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
}
